apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deploy
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: elmo3356/front-app:v1.2.3
          ports:
            - containerPort: 80                           
